//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSchool.Classes_
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScores
    {
        public int ScoreID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string GameName { get; set; }
        public int Score { get; set; }
        public Nullable<System.DateTime> DatePlayed { get; set; }
        public string Difficulty { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
