//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSchool.Classes_
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public int ID { get; set; }
        public string QuestionText { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public int CorrectAnswerIndex { get; set; }
        public int QuizID { get; set; }
    
        public virtual Quiz Quiz { get; set; }
    }
}
